### ISSUE TITLE
Set up semantic-release

### ISSUE THREAD

**Issue by TobiTenno** [cerner/cucumber-forge-report-generator#14]
### Description of Issue
For the purposes of automatic release, set up [semantic-release](https://github.com/semantic-release/semantic-release) to automatically evaluate commits and create releases on github & npm.

### Expected Outcomes
- [ ] Add travis stages & jobs for lint/test/release
- [ ] Set up `GH_TOKEN` and `NPM_TOKEN` on travis so that the releases can be automated.
- [ ] Do our first automated release through semantic-release

**Comment by jkuester** [comment]
Okay, I have been thinking about this quite a bit.  I think we should do this.  However, I wanted to see what you thought about having a separate `release` branch for the plugin to automatically run against?  Basically we make all of our commits to master as normal and then when we want to cut a release, we just fast-forward the release branch and let Travis and semantic-release do their thing.  

For this repo, I think we could get away with releasing every time we push to master, but I am looking for a process that we can easily apply to cucumber-forge-desktop as well.  For CFD I don't think we want to be cutting releases super often (even if we get the process fully automated) because the updates are visible to the app users and we don't want to bombard them.

**Comment by TobiTenno** [comment]
I don't think it makes sense, personally, for features to ever not be released. Or fixes, for that matter.

**Comment by jkuester** [comment]
Okay, just want to record the results of an offline conversation that @TobiTenno and I had.  Basically the plan is to not use semantic-release on CFD.  We are concerned that it will not play well with electron-forge (e.g. not sure about the ramifications of the package.json version not getting updated).  

For cucumber-forge-report-generator we can use semantic-release and run it as normal against the master branch.
